name: Generate and upload

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Build project
        run: bun install && bun run build

      - name: Upload using scp
        run: scp -r ./dist/*  ${{ secrets.SCP_USERNAME }}:${{ secrets.SCP_PASSWORD }}@ ${{ secrets.SCP_HOST }}:${{ secrets.SCP_TARGET }}
